### ISSUE TITLE
Creating app-deploy.yaml for appsody operator during appsody init

### ISSUE THREAD

**Issue by mtamboli** [appsody/appsody#260]
**Describe the bug**
Appsody operator needs needs app-deploy.yaml file for it to deploy the application to Kubernetes cluster.  Kabanero pipeline will fail for a simple application created using appsody as there is not app-deploy.yaml file. I think appsody init should create a simple template which can be extended later.

Sample app-deploy.yaml:
```
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: REPLACE-NAME
spec:
  applicationImage: 
  stack: java-microprofile
```

**Expected behavior**
A simple file app-deploy.yaml file should be created.

**Environment Details (please complete the following information):**
 OKD and Kabanero

**If applicable please specify:**
 all stacks

**Screenshots**

**Additional context**
