### ISSUE TITLE
Additional functionality for using Appsody CLI in Appsody Stacks CI release process

### ISSUE THREAD

**Issue by groeges** [appsody/appsody#498]
**Is your feature request related to a problem? Please describe.**
The Appsody stacks CI build and release process uses bash scripts to build the stack images and generate the stack assets (ie templates, index.yaml, etc). Recently the Appsody CLI has had some new commands added, `appsody stack package` and `appsody stack validate` which do very similar things to the CI scripts. It would be useful if we had only one process for building the stacks, and using the CLI is the best solution. However, the current implementation of these new commands are only capable of building a local version of these for testing purposes. Additional arguments are required to be added to these new commands  so that release ready version of the index.yaml, templates and docker images are generated.

**Describe the solution you'd like**
The Appsody CLI needs to be updated to generate these release ready versions of the index.yaml, templates and docker images. The current CI scripts generate a separate index file per repo, ie incubator-index.yaml, experimental-index.yaml etc and these contain http:// URLs which point to the location of the release assets, ie github.com etc. Also, the docker images that get created need to have the correct image registry org, so this would be `appsody` rather than `dev.local`. 

In order to do this we think the following arguments need to be able to be used with both the 'appsody stack package' and `appsody stack validate` (only used if the --no-package is not used - as they will need to be passed to the `appsody stack package` command).

--image_registry-org : default `dev.local`     
                                       when used in CI scripts would be `appsody` or `kabanero` etc
Image registry org defines the directory the index and assets will be created in, and will also define the org name for the docker images, ie appsody/java-microprofile  (or default dev.local/java-microprofile)

--repo-name  : default to dev-local
                           when used in CI scripts would be incubator, experimental, stable, kabanero etc.
This would define the name of the index file that will be used to store the release information, ie `--repo-name incubator` would generate/update an `incubator-index.yaml` file. The default would generate the `dev-local-index.yaml'

--release-url : default to file:/// url
                          when used in CI scripts would be  http://…../<release>/download/..... 
This will be used when generating the URLs for the release assets to be stored in the <repo-name>.index.yaml files.

If the following command is executed:
`appsody stack validate --repo-name incubator --image-registry-org appsody --release-url  https://github.com/appsody/stacks/releases/download/java-microprofile-v0.2.18` 

would generate an `incubator-index.yaml` with content similar to this:
```
apiVersion: v2
stacks:
  - id: java-microprofile
    name: Eclipse MicroProfile®
    version: 0.2.18
    description: Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
    license: Apache-2.0
    language: java
    maintainers:
      - name: Emily Jiang
        email: emijiang6@googlemail.com
        github-id: Emily-Jiang
      - name: Neeraj Laad
        email: neeraj.laad@gmail.com
        github-id: neeraj-laad
      - name: Ozzy
        email: ozzy@ca.ibm.com
        github-id: BarDweller
    default-template: default
    templates:
      - id: default
        url: https://github.com/appsody/stacks/releases/download/java-microprofile-v0.2.18/java-microprofile.v0.2.18.templates.default.tar.gz
```
as well as generating the dev-local-index.yaml with the file:/// URLs pointing to the local assets as is done today.

Having both the release index files (ie incubator-index.yaml, experimental-index.yaml) as well as the dev-local index files, will allow us to have the full assets and index files that will be  be pushed to the git release (without having to modify them outside the appsody CLI command) and the dev-local ones to be able to test the same images/assets locally.

Describe alternatives you've considered**

**Additional context**
