### ISSUE TITLE
Cannot set nodePort for service an app-deploy.yaml

### ISSUE THREAD

**Issue by mhdawson** [appsody/appsody#720]
**Describe the bug**
If you edit app-deploy.yaml to set the nodePort for the service it is not respected when you 
run appsody deploy

**To Reproduce**
1. create default app (ex node-express)
2. run appsody deploy
3. edit the app-deploy file to add nodePort:

```
 service:
    annotations:
      prometheus.io/scrape: "true"
    port: 3000
    nodePort: 32000
    type: NodePort
```
4. run appsody deploy

**Expected behavior**
service now uses the nodePort specifiied

**Actual behaviour**
random port is still selected, nodePort entry is removed from app-deploy.yaml

**Environment Details (please complete the following information):**
 - OS: linux/minikube

**If applicable please specify:**
user1@minikube1:~/test/appsody/test1$ appsody version
appsody 0.5.0

stack: node-express
N/A
**Additional context**
N/A
