### ISSUE TITLE
Environment variables with envFrom is not accepted.

### ISSUE THREAD

**Issue by haveroot** [appsody/appsody#808]
### What did you do?

Following the example as described in [Environment Variables](https://github.com/appsody/appsody-operator/blob/master/doc/user-guide.md#environment-variables), I added environment variables as shown below.

```yaml
  envFrom:
    - configMapRef:
      name: some.cfgmap
    - secretRef:
      name: some.secret
```

`appsody deploy` fails with this message 

```bash
spec.envFrom.configMapRef in body must be of type object: "null"
spec.envFrom.secretRef in body must be of type object: "null"
```

The above error message is actually consistent with the description of `envFrom` in the CR descripion [table](https://github.com/appsody/appsody-operator/blob/master/doc/user-guide.md#custom-resource-definition-crd).

### What did you expect to see?

Successful appsody deployment

### What did you see instead?

Failed appsody deployment

### Environment

* Appsody CLI version: `0.5.3`

* Appsody Stack: Custom

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-10-31T21:06:55Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by neeraj-laad** [comment]
@EnriqueL8 Can you please take a look at this one ?

**Comment by EnriqueL8** [comment]
Yes - I have been in contact with this person on slack, and haven't been able to reproduce this error just yet.

**Comment by EnriqueL8** [comment]
I believe it's the incorrect tabbing of values in the `YAML` file. Which means that when we `unmarshall` the YAML to update the labels of the deployment manifest, it cannot find the values under `envFrom` and replaces them with `{}`. The correct format looks like:
```
envFrom:
  - configMapRef:
      name: env-configmap
```

**Comment by chainhead** [comment]
Yes, the tabbing was the issue.

However, could you please confirm the if the table and description are in sync? Going by the table, I thought, this should be the structure.

```yaml
  envFrom:
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: estore.cfgmap
          key: cdc.app.port          
    - name: APP_PROFILE
      valueFrom:
        configMapKeyRef:
          name: estore.cfgmap
          key: cdc.app.profile          
```
