### ISSUE TITLE
appsody extract misses the .mvn folder

### ISSUE THREAD

**Issue by haveroot** [appsody/appsody#838]
**Describe the bug**
`appsody extract` command does not extract out the `.mvn` folder.

**To Reproduce**
Since this is w.r.t. a custom stack involving SpringBoot1 and OpenLiberty, I am unable to paste the stack details here. Nevertheless, if the stack has a folder named `.mvn` (or, any other folder with a leading dot in its name ?), it is not seen in the extracted folder when the `appsody extract` command has run.

I found this issue, when I was using a Tekton pipeline with a build step that uses the `appsody/appsody-buildah:0.2.1` where, the step looks like this. (Only one step shown for brevity.)

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: java-sb1ol-build-push-task
spec:
  inputs:
    params:
      - default: /workspace/extracted/Dockerfile
        name: pathToDockerFile
        type: string
      - default: /workspace/extracted
        name: pathToContext
        type: string
      - default: $HOME/.appsody/.appsody.yaml
        name: appsody-yaml-file-path
        type: string
    resources:
      - name: git-source
        type: git
  outputs:
    resources:
      - name: docker-image
        outputImageDir: /builder/home/image-outputs/docker-image
        type: image
  steps:
    - args:
        - '-c'
        - >
          echo "Checking for configmap
          value....DEFAULT_COLLECTION_IMAGE_REGISTRY_URL=$DEFAULT_COLLECTION_IMAGE_REGISTRY_URL"

          echo "appsody-yaml-file-path=$(inputs.params.appsody-yaml-file-path)"

          if [ -f "$(inputs.params.appsody-yaml-file-path)" ]

          then
              echo "Appsody yaml file $(inputs.params.appsody-yaml-file-path) exists."
          else
              echo "Appsody yaml file $(inputs.params.appsody-yaml-file-path) does not exists, we are creating it by running appsody list command."
              appsody version
          fi

          if [ -z "$DEFAULT_COLLECTION_IMAGE_REGISTRY_URL" ]

          then
              echo "DEFAULT_COLLECTION_IMAGE_REGISTRY_URL=$DEFAULT_COLLECTION_IMAGE_REGISTRY_URL given as input by user is empty, so using the registry for collection image download from $(inputs.params.appsody-yaml-file-path)"
          else
              #Replacing the container registry from index.docker.io to DEFAULT_COLLECTION_IMAGE_REGISTRY_URL for collection image download in the file inputs.params.appsody-yaml-file-path
              sed -i -e 's#images: .*$#images: $(DEFAULT_COLLECTION_IMAGE_REGISTRY_URL)#g' $(inputs.params.appsody-yaml-file-path)
              echo "sed command completed successfully"
                
              #Creating a cert for authentication of buildah login of the DEFAULT_COLLECTION_IMAGE_REGISTRY_URL registry url 
              echo "HOST=$DEFAULT_COLLECTION_IMAGE_REGISTRY_URL" > cert-creation.sh
              echo "sudo mkdir -p /etc/docker/certs.d/\${HOST}" >> cert-creation.sh
              echo "openssl s_client -connect \${HOST} -servername \${HOST} 2>/dev/null </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/docker/certs.d/\${HOST}/ca.crt" >> cert-creation.sh
              
              if [[ ( -z "$DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_USERNAME" ) || ( -z "$DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_PASSWORD" ) ]]
              then
                 echo "DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_USERNAME or DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_PASSWORD is empty ,Assumption is $DEFAULT_COLLECTION_IMAGE_REGISTRY_URL is internal registry, skipping the login to the registry"
              else
                 echo "Both DEFAULT_COLLECTION_IMAGE_REGISTRY_URL and Secrets are provided"
                 echo "Adding buildah login command to cert-creation.sh script"
                 echo "buildah login -u $DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_USERNAME -p $DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_PASSWORD \${HOST}" >> cert-creation.sh  
              fi
               chmod 755 cert-creation.sh
               ./cert-creation.sh
          fi

          /extract.sh
          
      command:
        - /bin/bash
      env:
        - name: gitsource
          value: git-source
        - name: DEFAULT_COLLECTION_IMAGE_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              key: default-collection-image-registry-url
              name: collection-image-registry-map
              optional: true
        - name: DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: default-collection-image-registry-secret
              optional: true
        - name: DEFAULT_COLLECTION_IMAGE_REGISTRY_SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: default-collection-image-registry-secret
              optional: true
      image: 'appsody/appsody-buildah:0.2.1'
      name: assemble-extract
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
        - mountPath: /config
          name: config-volume
        - mountPath: /etc/secret-volume
          name: secret-volume
```
After the extraction is completed, the custom Appsody stack is required to run a `./mvnw` command. However, this command fails with a `ClassNotFound` exception, because it does *not* find the `.mvn` folder in the extracted folder.

**Expected behavior**
The `.mvn` folder should have been available in the extracted folder. Currently, I am able to get the build step go through by forcing a `cp` command after the `/extract.sh` command.

**Actual behaviour**
I am able to confirm the missing `.mvn` folder by doing an `oc rsh` into the container that runs for the build step. See below.

```bash
sh-5.0# cd extracted/;ls -la
total 28
drwxr-xr-x. 4 root root  109 Jan  8 15:49 .
drwxrwxrwx. 5 root root   55 Jan  8 15:49 ..
-rw-r--r--. 1 root root  864 Jan  8 15:49 Dockerfile
-rwxr-xr-x. 1 root root  212 Jan  8 15:49 copy.sh
-rwxr-xr-x. 1 root root 7059 Jan  8 15:49 mvnw
-rwxr-xr-x. 1 root root 5007 Jan  8 15:49 mvnw.cmd
-rw-r--r--. 1 root root 3055 Jan  8 15:49 pom.xml
drwx------. 4 root root   30 Jan  8 15:49 src
drwxr-xr-x. 5 root root  188 Jan  8 15:49 user-app
sh-5.0# cd ../git-source/
sh-5.0# ls -la
total 48
drwxr-xr-x. 5 root root  188 Jan  8 15:48 .
drwxrwxrwx. 5 root root   55 Jan  8 15:49 ..
-rw-r--r--. 1 root root  115 Jan  8 15:48 .appsody-config.yaml
drwxr-xr-x. 8 root root  177 Jan  8 15:48 .git
-rw-r--r--. 1 root root   63 Jan  8 15:48 .gitignore
drwxr-xr-x. 3 root root   21 Jan  8 15:48 .mvn
-rw-r--r--. 1 root root  634 Jan  8 15:48 Dockerfile
-rw-r--r--. 1 root root 2904 Jan  8 15:48 README.md
-rw-r--r--. 1 root root 2852 Jan  8 15:48 app-deploy.yaml
-rwxr-xr-x. 1 root root 7059 Jan  8 15:48 mvnw
-rwxr-xr-x. 1 root root 5007 Jan  8 15:48 mvnw.cmd
-rw-r--r--. 1 root root 9023 Jan  8 15:48 pom.xml
drwxr-xr-x. 4 root root   30 Jan  8 15:48 src
```
Note that, the `extracted` folder does *not* have the `.mvn` folder.

**Environment Details (please complete the following information):**
- OpenShift: 4.2

**If applicable please specify:**
- Appsody: `appsody/appsody-buildah:0.2.1`
