### ISSUE TITLE
Generated `app-deploy.yaml` always has NodePort service

### ISSUE THREAD

**Issue by ianpartridge** [appsody/appsody#916]
When you run `appsody deploy`, Appsody generates an `app-deploy.yaml` file for you.

In the case of nodejs-express it looks a bit like this:

```yaml
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    ...
  labels:
    ...
spec:
  applicationImage: dev.local/test1
  createKnativeService: false
  expose: true
  livenessProbe:
    ...
  monitoring:
    ...
  readinessProbe:
    ...
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 3000
    type: NodePort
  stack: nodejs-express
  version: 1.0.0
status: {}
```

As you can see, Appsody generates a `NodePort` service by default. This means that the microservice will be accessible from outside the cluster when deployed.

This is fine in a basic development scenario, but consider the case when Appsody is being used with multiple microservices in a single application.  The developer will want more fine-grained control over which microservices are accessible from outside the cluster and which are not.  For those which should not be accessible from outside the cluster, a `ClusterIP` service should be created instead of a `NodePort`.

**Describe the solution you'd like**

An option to `appsody deploy` to allow the user to choose what sort of Kubernetes Service they want.  For example:

`appsody deploy --serviceType ClusterIP`

This would cause the generated `app-deploy.yaml` to include a ClusterIP definition.
