### ISSUE TITLE
Generated app-deploy.yaml does not contain recommended labels

### ISSUE THREAD

**Issue by ianpartridge** [appsody/appsody#917]
Currently, if your `.appsody-config.yaml` looks like this:

```yaml
project-name: proj
application-name: app
stack: docker.io/appsody/nodejs-express:0.4
```

When you do `appsody build` the following labels appear in the `AppsodyApplication` in `app-deploy.yaml`:

```yaml
  labels:
    image.opencontainers.org/title: proj
    app.appsody.dev/name: app
    stack.appsody.dev/id: nodejs-express
    stack.appsody.dev/version: 0.4.2
```

It is best practice for all Kubernetes resources (including custom resources like `AppsodyApplication`) to include standard labels - see https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

I believe the `AppsodyApplication` CR defined in `appsody-deploy.yaml` should contain these labels.

In particular, for this example:

```
app.kubernetes.io/name = proj
app.kubernetes.io/part-of = app
app.kubernetes.io/managed-by = appsody
```
