### ISSUE TITLE
Why do I need to appsody deploy to get a deploy yaml?

### ISSUE THREAD

**Issue by a-roberts** [appsody/appsody#92]
## Summary

I'm following https://appsody.dev/docs/using-appsody/building-and-deploying with a view to having code I can deploy through Tekton pipelines to my OpenShift cluster.

Why do I need to run `appsody deploy` (don't think I need to `appsody build` as well but I did) on my laptop to give me the appsody service yaml I need to check in to GitHub? 

Why not provide the service yaml as part of the stack template?

After doing an `appsody build` I need to `appsody deploy` (but I don't *really* want to deploy to my Mac, I just want an output file I'll check in and use later).

```
[Docker] Successfully tagged appsody:latest
Built docker image appsody
Tagging Docker image as dev.local/appsody
Generating the KNative yaml deployment file /Users/aroberts/appsody/appsody-service-255482510.yaml
Generated KNative serving deploy file: /Users/aroberts/appsody/appsody-service-255482510.yaml
Deploying your project to Kubernetes...
Running command: kubectl[apply -f /Users/aroberts/appsody/appsody-service-255482510.yaml]
[Error] kubectl apply failed: exit status 1 
[Error] Failed to deploy to your Kubernetes cluster: exit status 1
```

This is the output from the deploy (which has errored 😢), and I'm now going to rename the yaml before pushing it to GitHub to *really* deploy. 

This while process doesn't feel right to me, I don't see anything special in the deploy yaml I get either:

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: appsody
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/appsody
            imagePullPolicy: Never
            ports:
            - containerPort: 3000
```
