### ISSUE TITLE
The Stack's originally baked Docker Image URL should be overwrite-able by repository YAML

### ISSUE THREAD

**Issue by brightzheng100** [appsody/appsody#941]
**Describe the bug**
When trying to build a private Appsody Repo, it's common to compile a master repository YAML file and host the relevant components, as listed below, within the local environment too.
1. The Appsody repository master YAML file -> to be hosted in local Web Server
2. The templates of Stacks -> to be hosted in local Web Server
3. The Docker images of Stacks -> to be hosted in local Docker Registry

However, even the item 1 and 2 work perfectly fine, item 3 -- the Docker images of Stacks -- will still lookup for the one when Stack is `packaged`, by `appsody stack package --image-registry <HOST> --image-namespace <USER>`.
This makes rehosting the Stacks difficult and a repackage from scratch is a must.

**To Reproduce**
Let's take [incubator/java-spring-boot2](https://github.com/appsody/stacks/tree/master/incubator/java-spring-boot2) as an example.
This Stack's Docker image is published as `docker.io/appsody/java-spring-boot2:0.3`.
We then can compile a master repository YAML file and host it in local Web Server, as a private repository say named `private`, with all relevant components hosted locally:

```YAML
apiVersion: v2
stacks:
- id: java-spring-boot2
  name: Spring Boot®
  version: 0.3.26
  description: Spring Boot using OpenJ9 and Maven
  license: Apache-2.0
  language: java
  maintainers:
  - name: Erin Schnabel
    email: schnabel@us.ibm.com
    github-id: ebullient
  - name: Ozzy Osborne
    email: ozzy@ca.ibm.com
    github-id: bardweller
  - name: Richard Trotter
    email: rtrotter@us.ibm.com
    github-id: richard-trotter
  - name: Harish Yayi
    email: hyayi@us.ibm.com
    github-id: yharish991
  default-template: default
  src: http://localhost:8088/incubator.java-spring-boot2.v0.3.26.source.tar.gz
  templates:
  - id: default
    url: http://localhost:8088/incubator.java-spring-boot2.v0.3.26.templates.default.tar.gz
  - id: kotlin
    url: http://localhost:8088/incubator.java-spring-boot2.v0.3.26.templates.kotlin.tar.gz
  requirements:
    docker-version: '>= 17.09.0'
    appsody-version: '>= 0.5.0'
  image: localhost:5088/java-spring-boot2:0.3.26
```

If we issue the `appsody init private/java-spring-boot2`

```
$ appsody init private/java-spring-boot2
Checking stack requirements...
Docker requirements met
Appsody requirements met
Running appsody init...
Downloading java-spring-boot2 template project from http://localhost:8088/incubator.java-spring-boot2.v0.3.26.templates.default.tar.gz
Download complete. Extracting files from /Users/brightzheng/demos/kabanero/java-springboot/java-spring-boot2.tar.gz
Setting up the development environment
Your Appsody project name has been set to java-springboot
Pulling docker image docker.io/appsody/java-spring-boot2:0.3
Running command: docker pull docker.io/appsody/java-spring-boot2:0.3
...
```

As you can see, it would still try to pull the image from `docker.io/appsody/java-spring-boot2:0.3`, instead the one instructed by the repository file, which is `localhost:5088/java-spring-boot2:0.3.26`

**Expected behavior**
The `appsody init private/java-spring-boot2` command should respect the repository YAML file's `image:` element to pull the image from the specified place, which in this case is `localhost:5088/java-spring-boot2:0.3.26`, instead of the one originally published by `appsody stack package`.

**Actual behaviour**
Originally baked Docker image is pulled, which doesn't really respect the repository YAML file.

**Environment Details (please complete the following information):**
 - OS: Mac

**If applicable please specify:**
 - CLI version: appsody 0.5.8
 - Stack you are using: `java-spring-boot2`, but whatever Stack should be the same

**Screenshots**
N/A
