### ISSUE TITLE
Appsody deploy cmd can't detect exposed service URL in output logs

### ISSUE THREAD

**Issue by brightzheng100** [appsody/appsody#965]
**Describe the bug**

While using `ClusterIP` as service type:

```yaml
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: ClusterIP
```

The `appsody deploy` output logs would be wrong:

```sh
$ appsody deploy --no-build --namespace default
...
Attempting to get resource from Kubernetes ...
Running command: kubectl get route spring-boot-demo -o "jsonpath={.status.ingress[0].host}" --namespace default
Attempting to get resource from Kubernetes ...
Running command: kubectl get svc spring-boot-demo -o "jsonpath=http://{.status.loadBalancer.ingress[0].hostname}:{.spec.ports[0].nodePort}" --namespace default
Deployed project running at http://:
```

Please see the last line: `Deployed project running at http://:`

**Expected behavior**

Right detection should be applied with actionable advice to access the app deployed.

**If applicable please specify:**
 - CLI version: appsody 0.5.9
 - Stack you are using: springboot
