### ISSUE TITLE
Do not expose debug ports when running in k8s (in Codewind)

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#993]
**Describe the bug**

When an Appsody project is run from Codewind on k8s, the debug port is being exposed.  Take `nodejs-express` stack for example:

In `app-deploy.yaml`
```yaml
        ports:
        - containerPort: 9229
        - containerPort: 3000
```

In `app-service.yaml`
```yaml
  ports:
  - name: port-0
    port: 9229
    targetPort: 9229
  - name: port-1
    port: 3000
    targetPort: 3000
```

This is problematic for 2 reasons:

1. exposing debug port is a security issue
2. this is interfering with Codewind remote debug support; we are trying to do a kube port-forward to the port and we believe it is failing because the port is already "taken" by being already exposed

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**
